apiVersion: v2
name: voting-app-chart
description: A Helm chart for complete voting-app to deploy on Kubernetes


type: application
version: 0.1.0


appVersion: "1.16.0"

dependencies:
  - name: helm_vote
    version: "0.2.0"
    repository: "oci://registry-1.docker.io/vikasharya000"
  - name: helm_result
    version: "0.2.0"
    repository: "oci://registry-1.docker.io/vikasharya000"
  - name: helm_worker
    version: "0.2.0"
    repository: "oci://registry-1.docker.io/vikasharya000"
  - name: psql
    version: "0.1.0"
    repository: "oci://registry-1.docker.io/vikasharya000"
  - name: redis
    version: "0.1.0"
    repository: "oci://registry-1.docker.io/vikasharya000"
